name: Release
on:
  push:
    #branches: [master, main]
    tags: ["**"]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
          cache: sbt
      - uses: sbt/setup-sbt@v1
      - name: Install scala-native dependencies
        run: sudo apt-get install clang libstdc++-12-dev libgc-dev
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
      - run: sbt ci-release
        env:
          PGP_KEY_ID: ${{ secrets.PGP_KEY_ID }}
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          CI_SONATYPE_RELEASE: sonaUpload
      - name: Build Scaladoc
        run: sbt doc
      - name: Add CNAME for custom domain
        run: |
          mkdir -p ./jvm/target/scala-3.8.1/api/
          printf 'continuations4s.funfix.org\n' > ./jvm/target/scala-3.8.1/api/CNAME
      - name: Upload Scaladoc artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./jvm/target/scala-3.8.1/api/

  publish-scaladoc:
    needs: publish
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
